"""Tenant-aware authentication, CSRF protection, and administrator routes."""
import hmac
import os
import secrets
from functools import wraps

from flask import abort, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash

from .tenancy import EMS_ORG_ID

ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'admin123')
ALLOWED_IPS = os.environ.get('ALLOWED_IPS', '').split(',') if os.environ.get('ALLOWED_IPS') else []


def generate_csrf_token():
    if 'csrf_token' not in session:
        session['csrf_token'] = secrets.token_hex(16)
    return session['csrf_token']


def validate_csrf_token(token):
    return bool(token) and hmac.compare_digest(token, session.get('csrf_token', ''))


def check_ip_whitelist():
    if not ALLOWED_IPS or not ALLOWED_IPS[0]:
        return True
    client_ip = request.environ.get('HTTP_X_FORWARDED_FOR', request.environ.get('REMOTE_ADDR', ''))
    if ',' in client_ip:
        client_ip = client_ip.split(',', 1)[0].strip()
    return client_ip in ALLOWED_IPS


def is_super_admin_authenticated():
    return session.get('super_admin_authenticated') is True


def is_org_admin_authenticated():
    organization = getattr(g, 'organization', None)
    return bool(
        organization
        and session.get('organization_admin_org_id') == organization['org_id']
    )


def is_current_org_admin():
    return is_super_admin_authenticated() or is_org_admin_authenticated()


def _tenant_index_url():
    return url_for('tenant.index')


def _current_tenant_path():
    """Store only a local, route-derived tenant URL after login."""
    return request.full_path.rstrip('?')


def require_admin_auth(view):
    """Require super-admin or administrator for the currently resolved organization."""
    @wraps(view)
    def decorated_function(*args, **kwargs):
        if not check_ip_whitelist():
            flash('访问被拒绝：IP 地址不在白名单中', 'error')
            return redirect(_tenant_index_url())
        if not is_current_org_admin():
            session['pending_admin_continuation'] = _current_tenant_path()
            return redirect(url_for('tenant.admin_login'))
        return view(*args, **kwargs)
    return decorated_function


def require_csrf_protection(view):
    @wraps(view)
    def decorated_function(*args, **kwargs):
        if request.method == 'POST' and not validate_csrf_token(request.form.get('csrf_token')):
            flash('安全验证失败，请重试', 'error')
            return redirect(_tenant_index_url())
        return view(*args, **kwargs)
    return decorated_function


def register_security_routes(bp):
    """Attach tenant-local admin login/logout routes to the tenant blueprint."""

    @bp.route('/admin', methods=['GET', 'POST'])
    def admin_login():
        if not check_ip_whitelist():
            flash('访问被拒绝：IP 地址不在白名单中', 'error')
            return redirect(_tenant_index_url())

        if request.method == 'GET':
            if is_current_org_admin():
                return redirect(_tenant_index_url())
            session.setdefault('pending_admin_continuation', _tenant_index_url())
            return render_template('admin_login.html')

        if not validate_csrf_token(request.form.get('csrf_token')):
            flash('安全验证失败，请重试', 'error')
            return redirect(_tenant_index_url())

        password = request.form.get('password', '')
        # The deployment credential is valid everywhere and is deliberately checked first.
        if hmac.compare_digest(password, ADMIN_PASSWORD):
            session['super_admin_authenticated'] = True
            session.pop('organization_admin_org_id', None)
        else:
            org_hash = g.organization.get('admin_password_hash')
            # EMS retains its deployment credential only; other organizations use their own hash.
            if g.organization['org_id'] == EMS_ORG_ID or not org_hash or not check_password_hash(org_hash, password):
                flash('密码错误', 'error')
                return redirect(url_for('tenant.admin_login'))
            session['organization_admin_org_id'] = g.organization['org_id']
            session.pop('super_admin_authenticated', None)

        session.pop('admin_authenticated', None)  # Legacy claim must never grant authority.
        session.permanent = True
        continuation = session.pop('pending_admin_continuation', None)
        # It was generated by this server. A malformed session value cannot redirect externally.
        if not continuation or not continuation.startswith(f"/o/{g.organization['slug']}/"):
            continuation = _tenant_index_url()
        flash('管理员身份验证成功', 'success')
        return redirect(continuation)

    @bp.route('/admin/logout', methods=['POST'])
    @require_csrf_protection
    def admin_logout():
        session.pop('super_admin_authenticated', None)
        session.pop('organization_admin_org_id', None)
        session.pop('admin_authenticated', None)
        flash('已退出管理员模式', 'success')
        return redirect(_tenant_index_url())


def register_security_globals(app):
    @app.template_global()
    def csrf_token():
        return generate_csrf_token()

    @app.template_global()
    def is_admin_authenticated():
        return is_current_org_admin()

    @app.template_global()
    def template_is_org_admin_authenticated():
        return is_org_admin_authenticated()

    @app.template_global()
    def template_is_super_admin_authenticated():
        return is_super_admin_authenticated()

    # Existing templates expect these exact global names; avoid shadowing module helpers.
    app.jinja_env.globals['is_org_admin_authenticated'] = template_is_org_admin_authenticated
    app.jinja_env.globals['is_super_admin_authenticated'] = template_is_super_admin_authenticated


def get_security_status():
    return {
        'admin_authenticated': is_current_org_admin(),
        'super_admin_authenticated': is_super_admin_authenticated(),
        'csrf_enabled': True,
        'ip_whitelist_enabled': bool(ALLOWED_IPS and ALLOWED_IPS[0]),
        'allowed_ips': ALLOWED_IPS if ALLOWED_IPS and ALLOWED_IPS[0] else [],
        'admin_password_set': ADMIN_PASSWORD != 'admin123',
    }
